version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf
  - epub

build:
  apt_packages:
    - doxygen
