var annotated_dup =
[
    [ "date_s_t", "structdate__s__t.html", null ],
    [ "file_entry", "structfile__entry.html", null ],
    [ "fs_driver", "structfs__driver.html", null ],
    [ "gid_metadata", "structgid__metadata.html", null ],
    [ "HeapRegion", "struct_heap_region.html", null ],
    [ "hot_table", "structhot__table.html", null ],
    [ "linked_list_s_t", "structlinked__list__s__t.html", null ],
    [ "ll_node_s", "structll__node__s.html", null ],
    [ "screen_touch_status_s", "structscreen__touch__status__s.html", "structscreen__touch__status__s" ],
    [ "screen_touch_status_s_t", "structscreen__touch__status__s__t.html", null ],
    [ "set", "structset.html", null ],
    [ "time_s_t", "structtime__s__t.html", null ],
    [ "tskTaskControlBlock", "structtsk_task_control_block.html", null ],
    [ "v5_smart_device_s_t", "structv5__smart__device__s__t.html", null ],
    [ "xLIST", "structx_l_i_s_t.html", null ],
    [ "xLIST_ITEM", "structx_l_i_s_t___i_t_e_m.html", null ],
    [ "xMINI_LIST_ITEM", "structx_m_i_n_i___l_i_s_t___i_t_e_m.html", null ],
    [ "xSTATIC_EVENT_GROUP", "structx_s_t_a_t_i_c___e_v_e_n_t___g_r_o_u_p.html", null ],
    [ "xSTATIC_LIST", "structx_s_t_a_t_i_c___l_i_s_t.html", null ],
    [ "xSTATIC_LIST_ITEM", "structx_s_t_a_t_i_c___l_i_s_t___i_t_e_m.html", null ],
    [ "xSTATIC_MINI_LIST_ITEM", "structx_s_t_a_t_i_c___m_i_n_i___l_i_s_t___i_t_e_m.html", null ],
    [ "xSTATIC_QUEUE", "structx_s_t_a_t_i_c___q_u_e_u_e.html", null ],
    [ "xSTATIC_STREAM_BUFFER", "structx_s_t_a_t_i_c___s_t_r_e_a_m___b_u_f_f_e_r.html", null ],
    [ "xSTATIC_TCB", "structx_s_t_a_t_i_c___t_c_b.html", null ],
    [ "xSTATIC_TIMER", "structx_s_t_a_t_i_c___t_i_m_e_r.html", null ],
    [ "xTASK_PARAMETERS", "structx_t_a_s_k___p_a_r_a_m_e_t_e_r_s.html", null ],
    [ "xTASK_STATUS", "structx_t_a_s_k___s_t_a_t_u_s.html", null ],
    [ "xTIME_OUT", "structx_t_i_m_e___o_u_t.html", null ]
];